import { fetchRequestHandler } from '@trpc/server/adapters/fetch';

import { appRouter } from '@server/router';
import { createContext } from '@server/trpc';

/**
 * tRPC handler function to process incoming HTTP requests using the Fetch API adapter.
 *
 * This handler supports Next.js route handlers for both GET and POST methods.
 * It routes requests to the tRPC `appRouter` and creates the request context via `createContext`.
 *
 * @param {Request} req - The incoming HTTP request object.
 * @returns {Promise<Response>} - The HTTP response generated by tRPC.
 */
const handler = async (req: Request) => {
  return fetchRequestHandler({
    endpoint: '/api/trpc',
    req,
    router: appRouter,
    createContext
  });
};

export { handler as GET, handler as POST };
